#!/bin/bash
cat $1 | while read line
do
  echo "processing $line"
  echo $line >> done.txt
  s3uri=`echo $line | awk '{print $4}'`
  s3cmd get $s3uri 
  filename=`echo $s3uri | sed 's/s3:\/.*\///'`
  ./extract-faces $filename
  rm $filename
  mv *face*.jpg faces/
done

